version: '3'

services: 

  app:
    build:
      context: ./node
    container_name: app
    hostname: nodejsserver
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
     [3000:3000]
    #porta 3000 local aponta para porta 3000 do container
    depends_on:
      [db]
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    #se o container por algum motivo cair ele restarta
    restart: always
    #para conseguir rodar comandos de forma interativa
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: marcondesequandos/nginx:prod
    container_name: nginx
    hostname: nginx
    networks:
     - node-network
    ports: 
      - "8080:80"
    depends_on:
      [app]

networks:
  node-network:
    driver: bridge